FROM gcr.io/google.com/cloudsdktool/cloud-sdk

LABEL io.buildpacks.stack.id google
LABEL org.opencontainers.image.source https://github.com/jamesward/gcloud-buildpack

USER ${CNB_USER_ID}:${CNB_GROUP_ID}
