name: Build and Publish gcloud-buildpack

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build_and_publish_buildpack:
    name: Build and Publish gcloud-buildpack
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to GitHub Package Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup pack
        uses: buildpacks/github-actions/setup-pack@v5.3.1

      - name: Build and Publish
        run: pack package-buildpack --publish ghcr.io/jamesward/gcloud-buildpack
        working-directory: ./buildpack

# todo: can't override version so need to handle that
#
#      - id: register-settings
#        run: |
#          #!/usr/bin/env bash
#          set -euo pipefail
#          DIGEST="$(crane digest ${PACKAGE}:latest)"
#          echo "::set-output name=address::${PACKAGE}@${DIGEST}"
#        env:
#          PACKAGE: ghcr.io/jamesward/gcloud-buildpack
#
#      - name: Register
#        uses: docker://ghcr.io/buildpacks/actions/registry/request-add-entry:4.0.0
#        with:
#          token: ${{ secrets.CR_PAT }}
#          id: jamesward/gcloud
#          address: ${{ steps.register-settings.outputs.address }}
#          version: 0.0.1
